events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;

        ssl_certificate     /home/ivo/web2-cetvrti-projekt/lab4_project/ssl/certificate.crt;
        ssl_certificate_key /home/ivo/web2-cetvrti-projekt/lab4_project/ssl/private.key;

        root /home/ivo/web2-cetvrti-projekt/lab4_project/html/lab4;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
